
// call the assets endpoint for a static file in play

GET http://localhost:9000/assets/lib/requirejs/require.js
Accept: application/javascript
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
Host: localhost:9000
Accept-Language: en-US,en;q=0.9

// call for javascript file in play
GET http://localhost:9000/assets/javascripts/app.js
Accept: application/javascript
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
Host: localhost:9000


// call for css file in play
GET http://localhost:9000/assets/stylesheets/main.css
Accept: text/css,*/*;q=0.1
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
Host: localhost:9000
Accept-Language: en-US,en;q=0.9

// call for image file in play
GET http://localhost:9000/assets/images/logo.png
Accept: image/webp,image/apng,image/*,*/*;q=0.8
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
Host: localhost:9000


